### ISSUE TITLE
Start script sourcing from wrong location

### ISSUE THREAD

**Issue by theworkflow** [onmodulus/docker-run-meteor#9] opened 2016-06-06 14:24 UTC
Issue originally opened on the [modulus-cli](https://github.com/onmodulus/modulus-cli/issues/115#issuecomment-223856346) by @victorlambert

Hi guys, 

I'm trying the new modulus cli and meteor runtime.
Deployment is running fine but I get this error when starting the app (from the logs) : 

```
Now using node v0.10.41
Found package.json: ./.modulus/nvm/package.json
WARNING: Main file not specified in package.json.
WARNING: Looking for common main file names: index.js, app.js, server.js, main.js.
ERROR: No main or start script found. There is no application to run.
```

I do have a start script in my package.json : 

```
...
  "scripts": {
    "start": "meteor --settings settings-development.json",
...
```

Any idea ?
Thanks for the great work

**EDIT :** 
After downgrading to 5.0.1 and 5.0.0 I get the same error ... everything was working fine before I tried the new cli/runtime. Need to deploy today, hope I will find the issue.

**Comment by theworkflow** [comment] 2016-06-06 15:13
@victorlambert and @HynesIP can you send me your project ids so i can see the file structure? I just tried a few test deploys and they worked fine. It is a possibility you have selected the wrong runtime as well.

**Comment by theworkflow** [comment] 2016-06-06 15:17
@victorlambert your specified start script will not work in our environments. You can read our blog article on the [Meteor Runtime](http://blog.modulus.io/the-new-meteor-build-image)

**Comment by HynesIP** [comment] 2016-06-06 15:43
The project I was experiencing issues with is stable, now. Here's my rambling feedback about my experience:

I've been running hipaccess.com in production on a Node image, since 2013. I observed on my Node image dev platform for hipaccess that I was getting random "Unable to connect to any application instances". It appeared to me that some of the CLI 5.0 code was deploying a marginally stable build, since I was getting an odd Bad Gateway 502 error on builds. But it was working. I updated to CLI 6 and the build updated as if I was on a Meteor image. So, I was forced to move to a Meteor image on my dev project. It works and is stable now. I'll just have to move to a Meteor image on prod earlier than I intended to. I was hoping to make the move after you stopped calling it a Beta.

**Comment by victorlambert** [comment] 2016-06-07 08:36
@harlanj everything seems to be working fine now with modulus@6.0.0 and new meteor runtime. 

I didn't change anything, just renamed my start script to 'dev'. I read the article and I knew that this start script will not work in production (I'm just using it for development), I was just thinking that it might be in conflict as you are rebuilding package.json

**Comment by theworkflow** [comment] 2016-06-08 20:33
@victorlambert Sorry for the trouble. Open up another issue if your have more problems with our build/run images.

@HynesIP Thanks for the feedback! I'm glad that you've been with us since 2013! Your feedback is noted. If you continue to have these problems with builds failing due to gateway timeouts, I would contact support. That's more of an infrastructure problem rather than our build/run images not working properly. But if there's anything we can do to improve our processes please note those too. We greatly appreciate the feedback!

**Comment by ianserlin** [comment] 2016-06-09 22:14
I got the exact same error:

```
Now using node v0.10.41
Found package.json: ./.modulus/nvm/package.json
WARNING: Main file not specified in package.json.
WARNING: Looking for common main file names: index.js, app.js, server.js, main.js.
ERROR: No main or start script found. There is no application to run.
```

Meteor 1.3.2.4, modulus@6.0.0, meteor deploy target selected.

When this kinda stuff happens (usually once a month for at least one of our 20 apps on Modulus, also since 2013) I just scale down the project from one zone (like joyent) and up into another zone (like aws) and this forces a rebuild of the entire container and usually fixes the issue.

It would be cool if after failing X number of times, if the hosting system attempted to rebuild instead of reusing the container.

**Comment by theworkflow** [comment] 2016-06-15 14:38
@ianserlin can you email/comment your project id? We can take a look into your run image to make sure you're running the latest versions. This is something that has to be checked on the Modulus side. Sorry for the problems.

**Comment by sweetppro** [comment] 2016-06-22 18:15
Im having this issue also...
macapptracker-54313.onmodulus.net

downgrading to modulus-cli 5.0.1 doesn't get past compressing the project

**Comment by theworkflow** [comment] 2016-06-22 18:24
@sweetppro sorry you're having trouble. If you're not getting past the part where your project gets compressed and uploaded to our API then I would open up an issue with our CLI tool. This repo is used to actually run your project.

However, we are working on releasing this update soon to our application hosts. For now, I'll reopen the issue until this patch is live for everyone.

**Comment by joernroeder** [comment] 2016-06-23 10:16
same here…

```
WARNING: No package.json file found.
WARNING: Main file not specified in package.json.
WARNING: Looking for common main file names: index.js, app.js, server.js, main.js.
ERROR: No main or start script found. There is no application to run.
```

**Comment by oskareke** [comment] 2016-06-26 22:34
And me too..
WARNING: No package.json file found.
WARNING: Main file not specified in package.json.
WARNING: Looking for common main file names: index.js, app.js, server.js, main.js.
ERROR: No main or start script found. There is no application to run.

**Comment by joernroeder** [comment] 2016-06-27 07:39
i solved this by using the old 5.x version and think that the 6.0 cli should also inform the user upfront if the meteor version is incompatible.

**Comment by benstr** [comment] 2016-06-27 19:25
Solved this by downgrading to 5.x. 6.x would not treat the project as a meteor app. Meteor would never build, instead it was treated as a standard node app.

**Comment by joernroeder** [comment] 2016-06-27 22:04
@benstr yes! It used the demeteorizer to build the project. It is using an old meteor version which isn't suppported by the current meteor runtime and therfore the only way to run it.

**Comment by eeiswerth** [comment] 2016-07-13 05:49
Same issue for me. My app used to work fine. Updated modulus@next, converted my project to a Meteor runtime and tried to deploy and all I see is: 

Now using node v0.10.41
Found package.json: ./.modulus/nvm/package.json
WARNING: Main file not specified in package.json.
WARNING: Looking for common main file names: index.js, app.js, server.js, main.js.
ERROR: No main or start script found. There is no application to run.

Then I tried downgrading the cli tool to 5.0.0 and converted my project back to a Node runtime and same result.

My app used to work here: staging-53557.onmodulus.net

**Comment by eeiswerth** [comment] 2016-07-14 03:28
@harlanj Any ideas for a workaround with specific details?  I downgraded to Meteor 1.3.2.4 to see if that would make a difference, but I see the same error.

**Comment by sweetppro** [comment] 2016-07-14 07:01
i ended up migrating to scalingo.com, i just couldn't find a way around the problem

**Comment by eeiswerth** [comment] 2016-07-15 03:48
Looks like the problem was resolved with the following:

Modulus cli 6.2.0
Meteor 1.3.2.4
Meteor runtime in Modulus UI

Before deploying, stop your server. It seems that bringing down the server completely and then redeploying fixes the issue.

**Comment by sweetppro** [comment] 2016-07-15 06:47
Hmm i may migrate back of that's the case. Deploying is super quick and easy with modulus.

**Comment by lacco** [comment] 2016-07-22 07:26
I can confirm that this is working now, the instructions of @eeiswerth did help. 

To install Modulus CLI 6.2, I needed to do it via `npm -g install modulus@next`. The Meteor runtime can be changed in the Modulus project admin area (I wasn't aware that there is now Meteor-specific runtime). Afterwards, I needed to restart and redeploy my project a few times, but in the end it worked!

**Closed as completed** 2016-08-30 14:43 UTC
Labels: bug, reported
